language: python
jobs:
  include:
  - name: Code quality tests
    env: TOXENV=black,flake8,mypy
    python: 3.8
  - name: Unit tests with Python 3.8
    env: TOXENV=py38
    python: 3.8
  - name: Unit tests with Python 3.7
    env: TOXENV=py37
    python: 3.7
  - name: Unit tests with Python 3.6
    env: TOXENV=py36
    python: 3.6
  - stage: build
    script: poetry build
    deploy:
      - provider: releases
        token:
          secure: mWuUBXLwcJ4xOdnrT9wJBFDLIYZMfRLfeBrYqOOfF2Y7r2VpqSEkfeqoKm1P+K5k/wwRVRZzBhbIyplQ73lF/s22DdNAfM4O0e47ElmitdjVWboghfPr3O5aBykDh1RsYDHLtwdFSDldI+EZOjs2Ml/obQVEc8gEIDh2y2PcnJS235NRx5LamVTXMxukzyb4U9SPGDqumXyvxNWWZmCr3A/+dqQQ7WTrTl3sadarDxSeSZdUzBFDXyWxaqRkoGHQ3mBMHgPXoMEH/Mz9lukNyQOhg8bs9jTFISOimSmdVg9MLX5mD5S2VqXXcPYhpVnXpvNYB8Iolgzp+QoRNeVH6pyvXae2FwgYL58lQmqU1z99662Doz7a2IcxXWRUKPkXJ6mnHVE2uEhRR24LWYdlHc4AgkRygLYYi6I1NRhIFrORydmmYMB4ZIQINDkrhmtkjGlYDrkyEiHY6lNT9rA65MEb4ubdZYEuYFuaKWYt5L1oLGgs8MQEkwksEjTSBwqZwNW0A/PwuGg1bKTXpTnt1uFsbbgFzKofxBr5X3CzsndmYu8VP9KqoOqe9E8bEr6hyRsym/6S5ViofoiQRjQ+87Em3l1GjAZiWyqomYCaqoRdINhubaRUFSuM7T97kwvRC/DSOYIkUsYnlj0vij6GQNNUet5K1UnCdfeSVlYW3pc=
        file_glob: true
        file: dist/*
        on:
          tags: true
          branch: master
          repo: gzzo/graphql-sqlalchemy

      - provider: pypi
        distributions: sdist bdist_wheel
        on:
          tags: true
          branch: master
          repo: gzzo/graphql-sqlalchemy

        skip_existing: true
        username: "__token__"
        password:
          secure: DvdiCJyBfKbw/IncE5jZv0EpQLYBbmg200B8eYJAWuF6+Zm8ey/brNuLzPACVQwSBUmyzg6hN3V6uhWnhwpzWnl3GOmIQQj2CP9VbXoehKgO1DOq6mRwyfHXJjJy4REmfdkEdXHtAndJNvFB/1LSpn5Qdb7DZrQmTrOB9NaJHgPbw3DgNBzYtDu+sUEn8MpRvmVW6H1LH7wsmp5A0iySz6n0rm2vz0altGYiaDC+QMg2XB8iQPzlSVqO67Jzh6eSrYl4d9ld1XfbuO5NILfXcRJB9XowCHfkI5mH+glAAW1RGDDAEvjVg1qzkCHCEgcpaUnqfwX0zWkww8i/aRCCkoMsFKMEyc6g1cAs/WueZGiNLUKnzwJJr211CUmTT0wINtsJ3ikzVKdJlnkHyQ2GALTBGrNsK9jbD+E0xbBYshFcbXxzARjg6ZrMOYVki0nM+ljHYcVZ6OdCEf/93MNWRaXOq4sfQMkwoEpRsruL9E0HaI8TwNq3ZuOCTc1JQnBR/qTLKuv9/peo++Rb+ww6QTrpPPY0LDj5x/pjLHFOqENV0AUzm41C4XTy7DvaE1ozTDTd4EQXvlzRiHDqTPFJKV9+VtmOVkpb/r+D2l7GZn3h7G29aCRGKPR/axcpBVMg1uqrofFPzmF9UsD8diKUKDFsDHXitxpkWddO4HjZiOY=

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install:
- pip install "poetry>=1,<2"
- poetry install
script:
- tox -e $TOXENV
after_success:
- codecov
