language: python
jobs:
  include:
  - name: Code quality tests
    env: TOXENV=black,flake8,mypy
    python: 3.8
  - name: Unit tests with Python 3.8
    env: TOXENV=py38
    python: 3.8
    after_success:
      - codecov
  - name: Unit tests with Python 3.7
    env: TOXENV=py37
    python: 3.7
  - name: Unit tests with Python 3.6
    env: TOXENV=py36
    python: 3.6
  - stage: deploy
    script: poetry --build publish
    if: (tag =~ ^v) AND (branch = master)
    deploy:
      - provider: releases
        token:
          secure: mWuUBXLwcJ4xOdnrT9wJBFDLIYZMfRLfeBrYqOOfF2Y7r2VpqSEkfeqoKm1P+K5k/wwRVRZzBhbIyplQ73lF/s22DdNAfM4O0e47ElmitdjVWboghfPr3O5aBykDh1RsYDHLtwdFSDldI+EZOjs2Ml/obQVEc8gEIDh2y2PcnJS235NRx5LamVTXMxukzyb4U9SPGDqumXyvxNWWZmCr3A/+dqQQ7WTrTl3sadarDxSeSZdUzBFDXyWxaqRkoGHQ3mBMHgPXoMEH/Mz9lukNyQOhg8bs9jTFISOimSmdVg9MLX5mD5S2VqXXcPYhpVnXpvNYB8Iolgzp+QoRNeVH6pyvXae2FwgYL58lQmqU1z99662Doz7a2IcxXWRUKPkXJ6mnHVE2uEhRR24LWYdlHc4AgkRygLYYi6I1NRhIFrORydmmYMB4ZIQINDkrhmtkjGlYDrkyEiHY6lNT9rA65MEb4ubdZYEuYFuaKWYt5L1oLGgs8MQEkwksEjTSBwqZwNW0A/PwuGg1bKTXpTnt1uFsbbgFzKofxBr5X3CzsndmYu8VP9KqoOqe9E8bEr6hyRsym/6S5ViofoiQRjQ+87Em3l1GjAZiWyqomYCaqoRdINhubaRUFSuM7T97kwvRC/DSOYIkUsYnlj0vij6GQNNUet5K1UnCdfeSVlYW3pc=

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
install:
- pip install "poetry>=1,<2"
- poetry install
script:
- tox -e $TOXENV
