language: python
jobs:
  include:
    - name: Code quality tests
      env: TOXENV=black,flake8,mypy
      python: 3.8
    - name: Unit tests with Python 3.8
      env: TOXENV=py38
      python: 3.8
    - name: Unit tests with Python 3.7
      env: TOXENV=py37
      python: 3.7
    - name: Unit tests with Python 3.6
      env: TOXENV=py36
      python: 3.6
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install "poetry>=1,<2"
  - poetry install
script:
  - tox -e $TOXENV
after_success:
  - codecov
